RDKVREFPLT-3981: Fix the rfc caused build error (#378)
* RDKVREFPLT-3981: Fix the rfc caused build error

Reason for Change: git/rfcMgr/mtlsUtils.cpp:69:29: error: unused parameter 'sec' [-Werror=unused-parameter] Please see ticket for more details.
Test Procedure: Verify CI Build integrity.

* RDKVREFPLT-3941: update rfc comp rev to fix build error

Reason for Change: update RFC component version to include the build fix.
Test Procedure: Verify build integrity.

* RDK-54694: rfc build error fix for unused parameter

Reason for Change: Fix for git/rfcMgr/mtlsUtils.cpp:69:29: error: unused parameter 'sec' [-Werror=unused-parameter]
Test Procedure: Verify build integrity without disabling the security flags.